### ISSUE TITLE
Awesome 4 support

### ISSUE THREAD

**Issue by 4ban** [stobenski/pro#10]
Hello, will you port theme to 4th version of awesome wm?

https://awesomewm.org/apidoc/documentation/17-porting-tips.md.html#v4

**Comment by stobenski** [comment]
Hello, sorry, but no. Ain't got no time for that. I'm stuck in 3.5.*

Feel free to fork.

**Comment by 4ban** [comment]
Hello again, after so much time. I'm still interested to port it to awesome 4, but I need you to add a license for that. For example, short and permissive MIT.

**Comment by stobenski** [comment]
Done.
